# The URL the site will be built for
base_url = "https://rigille.pages.dev"

compile_sass = true
title = "Rígille's Blog"
description = "A clean, responsive theme"
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
author = "Rígille S. B. Menezes"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "Rígille's Blog"
katex_enable = true
katex_auto_render = true
